version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cafe_db
    environment:
      POSTGRES_USER: cafe_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: cafe_pos
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: